project_name: nssh
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/nssh/main.go
    binary: nssh
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/0x6b/nssh/cmd.Commit={{.ShortCommit}}'
      - -X 'github.com/0x6b/nssh/cmd.Tag={{.Tag}}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
